config/routes.rb
Rails.application.routes.draw do
 resources :books
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#top'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      @books=Book.all
      render :index
    end
  end
  
  def index
    @books = Book.all
    @book=Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    book=Book.find(params[:id])
    
      if book.update(book_params)
      flash[:update]= "Book was successfully updated."
      redirect_to book_path(book.id)
    else
      @book=book
      
      render :edit
      
    end
    
  end
  
  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %> 
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book,　local: true do |f| %>

<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>

<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<head>
 <style>
ul{
  padding-left:0;
}

li{
  list-style:none;
}

 table {
    width: 80%; 
   
    border-collapse: collapse;
  }

  th, td {
   
    padding: 8px;
    text-align: left;
  }

  
  
  td {
    width: 33.33%;
    word-wrap: break-word; 
  }


  td:first-child {
    width: 150px; 
  }
</style>
</head>



<h1>Books</h1>

<table>
 <tr>
  <th>Title</th>
  <th>Body</th>
  <th></th>
 </tr>

<% @books.each do |book| %>

<tr>
 <td><%= book.title %></td>
 <td><%= book.body %></td>
 <td>
  <%= link_to "Show", book_path(book.id) %>
  <%= link_to "Edit", edit_book_path(book.id) %>
  <%= link_to "Destroy",book_path(book.id), method: :delete, "data-confirm" => "Are yu sure?" %>
  </td>
</tr>



<% end %>

</table>

<h2>new book</h2>

<% if @book.errors.any? %> 
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: Book.new , url: '/books', method: :post do |f| %>
 <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Body</h4>
  <%= f.text_area :body %>
	<br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<%= flash[:notice] %>
<%= flash[:update] %>
<p>Title:
    <span><%= @book.title %></span>
</p>

<p>Body:
    <span><%= @book.body %></span>
</p>


<%= link_to "Edit|", edit_book_path(@book.id) %>

<%= link_to "Back", books_path %>

app/views/homes/top.html.erb
<h2>ようこそ　Bookersへ!</h2>

<p>Bookersでは、さまざまな書籍にかんするあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<br>

<%= link_to 'start', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>